version: "3.9"

networks:
  local_network:
    name: local_network

services:
  workspace:
    build: ../Dockerfile
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - "3000:3000"
    networks:
      - local_network
    tty: true
