# Default values for vdr-proxy prod deployment
namespace: c2a2c4-prod

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
podLabels: {}

image:
  pullPolicy: IfNotPresent
  registry: artifacts.developer.gov.bc.ca/github-docker-remote
  # registry: ghcr.io
  repository: bcgov/indy-vdr-proxy-server/server
  # Overrides the image tag whose default is the chart appVersion.
  tag: "b340416"

env:
  PORT: "3000"
  THROTTLE_TTL: "60000"
  THROTTLE_LIMIT: "2000"
  LOG_LEVEL: "2"

resources:
  requests:
    memory: 300Mi
    cpu: 50m
  limits:
    memory: 300Mi
    cpu: 200m

imagePullSecrets:
  - name: artifactory-regcred

service:
  targetPort: 3000

route:
  host: ""
  annotations:
    haproxy.router.openshift.io/timeout: 60s

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
